openapi: "3.0.0"
info:
  version: 1.0.0
  title: oasfragmentdesign
paths: {}
components: 
  examples:
      FligthExample:
        value: 
          ID: "AA980"

  schemas:
      Flight:
          type: object
          description: Flight
          properties:
              ID: 
              
                type: string
